name: List Docker Repository Tags
description: |
  This action calls the Docker Registry API v2 to list the tags of a repository.
inputs:
  token:
    description: The Docker registry authorization token.
    required: true
  registry:
    description: |
      The registry to make the request against. Example: public.ecr.aws
    required: true
  repository:
    description: |
      The Docker image repository. Example: library/ubuntu
    required: true
outputs:
  tags:
    description: JSON formatted list of tags for the docker repository.
    value: ${{ steps.list-docker-tags.outputs.tags }}
runs:
  using: "composite"
  steps:
    - id: list-docker-tags
      run: |
        response=$(curl -L -H 'Authorization: Bearer ${{ inputs.token }}' -X GET https://${{ inputs.registry }}/v2/${{ inputs.repository }}/tags/list)
        tags=$(echo "${response}" | jq -e -c '.tags')
        echo "tags=${tags}" >> "{GITHUB_OUTPUT}"
      shell: bash
