name: Self test

on:
  push: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  self-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - id: composite-action
        uses: ./
        with:
          example-input: Hello?
      - run: |
          echo ${{ steps.composite-action.outputs.example-output }}
